FROM ruby:3.2

RUN apt-get update \
	&& apt-get upgrade -yq \
	&& apt-get install -y --no-install-recommends \
		postgresql-client \
	&& apt-get clean -qy \
	&& rm -rf /var/lib/apt/lists/*

RUN mkdir /app
WORKDIR /app
COPY Gemfile* /app/
RUN gem update bundler && bundle install

# Keep Plek happy
ARG GOVUK_APP_DOMAIN=''
ARG GOVUK_WEBSITE_ROOT=''

ARG RAILS_ENV
RUN if [ "$RAILS_ENV" = "production" ]; then bundle exec rake assets:precompile; fi

CMD ["rails", "server", "-b", "0.0.0.0"]
